In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("housingprice.csv")

In [3]:
df.head()

Area   Price
0  2500  520000
1  3000  570000
2  2600  500000
3  3100  550000
4  4000  580000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['Area']],df.Price)

LinearRegression()

In [6]:
model.coef_

array([50.15822785])

In [8]:
model.intercept_

387790.08438818564

In [10]:
model.predict([[5500]])

array([663660.33755274])

In [11]:
import pickle

In [14]:
with open('model_pickle' ,'wb') as f:
    pickle.dump(model,f)

In [16]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [18]:
mp.predict([[5500]])

array([663660.33755274])

In [23]:
import joblib

In [25]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [26]:
mj = joblib.load('model_joblib')

In [28]:
mj.predict([[5500]])

array([663660.33755274])